name: 'VPC Deployment'

on:
  workflow_dispatch:
  
#on:
  #push:
    #branches: [ "main" ]
  #pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: Day-One/vpc/
      run: terraform init -backend-config "bucket=dj1bucket" -backend-config "key=eks-prod.tfstate"
           
    - name: Terraform Format
      working-directory: Day-One/vpc/
      run: terraform fmt

    - name: Terraform Plan
      working-directory: Day-One/vpc/
      run: |
        plan=$(terraform plan -no-color -input=false)
        echo "plan<<EOF" >> $GITHUB_OUTPUT
        echo "$plan" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Show Terraform Plan Output
      run: echo "${{ steps.plan.outputs.plan }}"
    
    - name: Terraform Apply
      working-directory: Day-One/cluster/
      run: terraform apply -var="k8sVersion=1.33" -auto-approve
